# -*- coding: utf-8 -*-
"""Copy of Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBIeeXCQU67zeUjylCnig-X1XPA74x2l

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** [Sahrul Ramdani]
- **Email:** [CDCC200D6Y2678@student.devacademy.id]
- **ID Dicoding:** [CDCC200D6Y2678]

## Menentukan Pertanyaan Bisnis

**SMART Question** adalah sebuah framework untuk merumuskan pertanyaan secara terstruktur agar memeperoleh informasi yang mendalam.

* **Spesific (Spesifik)**
  * Pertanyaan harus jelas, fokus pada sebuah topik tertentu, dan tidak bermakna ganda. Hindari pertanyaan yang terlalu luas.
    * Salah: Bagaimana cara meningkatkan penjualan?
    * Benar: Faktor apa saja yang memengaruhi penurunan penjualan produk kategori elektronik di wilayah Jakarta selama kuartal terakhir?
* **Measurable (Terukur)**
  * Pertanyaan harus bisa dijawab dengan angka atau matrix yang konkret, harus tahu apa yang akan dihitung.
    * Salah: Apakah pelanggan senang dengan layanan kita?
    * Benar: Berapa skor rata-rata Customer Satisfaction untuk layanan purna jual bulan ini dibandingkan bulan lalu?
* **Action-Oriented (Berorientasi Aksi)**
  * Hasil dari pertanyaan harus bisa memberikan arahan untuk melakukan tindakan nyata. Jika pertanyaan terjawab, stakeholder harus tahu apa langkah selanjutnya.
    * Salah: Mengapa orang suka berbelanja?
    * Benar: Fitur apa pada aplikasi yang paling sering digunakan sebelum pengguna memutuskan untuk melakukan checkout?
* **Relevant (Relevan)**
  * Hasil dari pertanyaan harus sejalan dengan tujuan utama bisnis atau masalah yang sedang dihadapi.
    * Salah: Menanyakan tentang stok gudang saat masalah utamanya adalah efektivitas kampanye media sosial.
    * Benar: Apakah kampanye iklan di Instagram memberikan Return on Ad Spend (ROAS) yang lebih tinggi dibandingkan iklan di TikTok?
* **Time-bound (Terikat Waktu)**
  * Pertanyaan harus ada batasan waktu yang jelas agar analisis memiliki konteks yang tepat.
    * Salah: Berapa banyak pengguna baru kita?
    * Benar: Berapa tingkat pertumbuhan pengguna baru secara bulanan (Month-over-Month) sepanjang tahun 2025?

**Contoh pertanyaan bisnis yang memenuhi seluruh elemen SMART**

***"Faktor apa saja yang memengaruhi penurunan conversion rate pada pengguna aplikasi Android di wilayah Jabodetabek sebesar 5% selama periode Flash Sale Maret 2026?"***

Keterangan:

- **Specific**: Fokus pada "penurunan conversion rate" untuk "aplikasi Android" di "Jabodetabek". Bukan sekadar penjualan turun.
- **Measurable**: Ada angka konkret yang ingin dianalisis, yaitu penurunan sebesar "5%".
- **Action-Oriented**: Dengan mengetahui faktor penyebabnya misalnya bug pada versi Android tertentu atau kendala logistik di Jabodetabek, tim bisa langsung melakukan perbaikan teknis atau operasional.
- **Relevant**: Penurunan konversi saat Flash Sale adalah masalah kritis bagi bisnis retail/e-commerce.
- **Time-bound**: Dibatasi pada periode spesifik "Flash Sale Maret 2026".

*   **Pertanyaan 1: Optimalisasi Operasional Berdasarkan Jam Sibuk**

***"Jam berapa saja yang termasuk dalam kategori peak hour (puncak tertinggi) yang menyumbang 70% dari total peminjaman sepeda pada hari kerja (workingday = 1) selama periode 2 tahun (2011-2012), dan bagaimana strategi penjadwalan ulang sepeda (rebalancing) yang paling tepat untuk mengatasi lonjakan permintaan di jam-jam tersebut?"***

Keterangan:

- **Specific**: Analisis ini fokus pada hari kerja (workingday = 1) dan ingin mengidentifikasi jam-jam spesifik (misalnya: jam 7-8 pagi, jam 17-18 malam) yang menjadi penyumbang terbesar peminjaman. Bukan sekadar "jam sibuk", tapi jam sibuk pada hari kerja.

- **Measurable**: Targetnya jelas secara kuantitatif, yaitu "70% dari total peminjaman". Tim analis dapat menghitung kumulatif persentase peminjaman per jam dan menentukan batas jam mana saja yang mencapai angka 70%. Metrik yang digunakan adalah cnt (jumlah peminjaman) per hr.

- **Action-Oriented**: Jika peak hour terjadi pada jam 07.00 - 09.00, maka aksi nyata yang bisa dilakukan adalah memastikan truk operasional sudah selesai memindahkan sepeda dari stasiun pusat kota ke stasiun pemukiman sebelum jam 06.30 pagi. Jika puncak sore terjadi pada jam 17.00 - 19.00, maka aksi nyata adalah mempersiapkan tim untuk memindahkan sepeda kembali ke pusat kota pada jam 15.00 - 16.00.

- **Relevant**: Masalah ketidakseimbangan ketersediaan sepeda (penumpukan di satu stasiun dan kekosongan di stasiun lain) adalah inti dari tantangan operasional bisnis bike sharing. Pemecahan masalah ini berdampak langsung pada retensi pelanggan dan efisiensi biaya operasional.

- **Time-bound**: Analisis menggunakan data selama 2 tahun (2011-2012). Rentang waktu ini cukup panjang untuk melihat pola yang konsisten, menghilangkan anomali musiman, dan menghasilkan rekomendasi yang valid untuk jangka panjang.




*   **Pertanyaan 2: Strategi Mitigasi Risiko dan Promosi Berbasis Cuaca**

***"Faktor cuaca spesifik apa (dari kolom weathersit dan hum) yang paling dominan menyebabkan penurunan jumlah peminjaman sepeda lebih dari 50% pada akhir pekan (workingday = 0) di musim gugur (season = 3), dan jenis promo atau insentif apa yang paling efektif untuk mendorong peminjaman di kondisi tersebut?"***

Keterangan:

- **Specific**: Pertanyaan ini tidak sekadar menanyakan "apakah cuaca berpengaruh?". Pertanyaan ini mengerucut pada kondisi spesifik: yaitu weekend (workingday = 0) di musim gugur (season = 3). Ini penting karena persepsi orang terhadap cuaca buruk di akhir pekan (leisure time) berbeda dengan di hari kerja (commute time).

- **Measurable**: Ada angka yang jelas, yaitu "penurunan lebih dari 50%" (dibandingkan dengan rata-rata peminjaman di musim gugur saat cuaca cerah). Analis dapat menghitung rata-rata cnt untuk setiap nilai weathersit (1:Cerah, 2:Berkabut, 3:Hujan Ringan) dan mengukur persentase penurunannya. Kelembaban (hum) juga bisa dianalisis secara numerik.

- **Action-Oriented**: Jika ternyata faktor dominannya adalah "Kelembaban > 80% + Kabut", maka tim marketing bisa mengotomatisasi sistem notifikasi push: "Hey, it's foggy but fun! 20% off for your next ride." Jika faktor dominannya adalah "Hujan Ringan", tim bisa menyiapkan promo "Rainy Day Loyalty Points" (poin ganda) untuk mendorong peminjaman.

- **Relevant**: Data historis menunjukkan penjualan sangat fluktuatif tergantung cuaca. Bagi manajemen, memiliki strategi anti-fragile terhadap cuaca buruk adalah keunggulan kompetitif. Hal ini relevan untuk menjaga pendapatan tetap stabil sepanjang tahun meskipun cuaca sedang tidak bersahabat.

- **Time-bound**: Analisis difokuskan pada musim gugur (season = 3). Musim ini unik karena sering terjadi perubahan cuaca ekstrem (dari cerah ke hujan) yang sulit diprediksi. Dengan menganalisis musim ini secara spesifik, perusahaan dapat mempersiapkan strategi khusus di bulan-bulan September, Oktober, dan November.

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

"""## Data Wrangling

### Gathering Data

#### Load df ...
"""

df_hour = pd.read_csv('/content/hour.csv')
print(f"   - Jumlah baris: {df_hour.shape[0]:,}")
print(f"   - Jumlah kolom: {df_hour.shape[1]}")

df_day = pd.read_csv('/content/day.csv')
print(f"   - Jumlah baris: {df_day.shape[0]:,}")
print(f"   - Jumlah kolom: {df_day.shape[1]}")

display(df_hour.head())
display(df_day.head())

"""**Insight:** (PERBEDAAN DATA)
- hour.csv: 17.379 baris dan 17 kolom (data per jam) - cocok untuk analisis pola harian
- day.csv: 731 baris dan 16 kolom (data per hari) - cocok untuk analisis tren jangka panjang

### Assessing Data

#### Identifying ... problem
"""

# ---------------------------------------------------------------------
# PROBLEM 1: CEK TIPE DATA
# ---------------------------------------------------------------------
print("\n PROBLEM 1 CEK TIPE DATA")
print("-"*50)

print("\nTipe data hour.csv:")
print(df_hour.dtypes)

print("\nTipe data day.csv:")
print(df_day.dtypes)

# Identifikasi kolom dengan tipe data kurang tepat
wrong_types_hour = df_hour.dtypes[df_hour.dtypes == 'object'].index.tolist()
wrong_types_day = df_day.dtypes[df_day.dtypes == 'object'].index.tolist()

print(f"\n Kolom dengan tipe 'object' di hour.csv: {wrong_types_hour}")
print(f" Kolom dengan tipe 'object' di day.csv: {wrong_types_day}")
print("→ Masalah: Kolom tanggal (dteday) seharusnya bertipe datetime, bukan object/string")

# ---------------------------------------------------------------------
# PROBLEM 2: CEK MISSING VALUES
# ---------------------------------------------------------------------
print("\n PROBLEM 2 CEK MISSING VALUES")
print("-"*50)

missing_hour = df_hour.isnull().sum()
missing_day = df_day.isnull().sum()

print(f"\nMissing values di hour.csv: {missing_hour.sum()} dari {len(df_hour)} baris")
print(f"Missing values per kolom di hour.csv:\n{missing_hour[missing_hour > 0]}")

print(f"\nMissing values di day.csv: {missing_day.sum()} dari {len(df_day)} baris")
print(f"Missing values per kolom di day.csv:\n{missing_day[missing_day > 0]}")

if missing_hour.sum() == 0 and missing_day.sum() == 0:
    print("\n Tidak ditemukan missing values pada kedua dataset!")

# ---------------------------------------------------------------------
# PROBLEM 3: CEK DATA DUPLIKAT
# ---------------------------------------------------------------------
print("\n PROBLEM 3 CEK DATA DUPLIKAT")
print("-"*50)

duplicate_hour = df_hour.duplicated().sum()
duplicate_day = df_day.duplicated().sum()

print(f"Data duplikat di hour.csv: {duplicate_hour} baris")
print(f"Data duplikat di day.csv: {duplicate_day} baris")

if duplicate_hour == 0 and duplicate_day == 0:
    print("\n Tidak ditemukan data duplikat pada kedua dataset")

# ---------------------------------------------------------------------
# PROBLEM 4: CEK OUTLIER DENGAN METODE IQR
# ---------------------------------------------------------------------
print("\n PROBLEM 4 CEK OUTLIER PADA KOLOM NUMERIK")
print("-"*50)

def check_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return len(outliers), len(outliers)/len(data)*100, lower_bound, upper_bound

numeric_columns = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']

print("\nHasil deteksi outlier pada hour.csv:")
print("-"*40)
for col in numeric_columns:
    n_outliers, pct_outliers, lb, ub = check_outliers(df_hour, col)
    status = " ADA OUTLIER" if n_outliers > 0 else " AMAN"
    print(f"{col:12} | Outlier: {n_outliers:5} ({pct_outliers:5.2f}%) | {status}")

# ---------------------------------------------------------------------
# PROBLEM 5: CEK KONSISTENSI DATA (casual + registered = cnt)
# ---------------------------------------------------------------------
print("\n PROBLEM 5 CEK KONSISTENSI DATA")
print("-"*50)

inconsistent = df_hour[df_hour['casual'] + df_hour['registered'] != df_hour['cnt']]
print(f"Jumlah baris dengan casual + registered ≠ cnt: {len(inconsistent)}")

if len(inconsistent) == 0:
    print(" Data konsisten, casual + registered = cnt untuk semua baris.")
else:
    print(f" Ditemukan {len(inconsistent)} baris yang tidak konsisten!")
    display(inconsistent.head())

# ---------------------------------------------------------------------
# PROBLEM 6: CEK KONSISTENSI HOLIDAY VS WORKINGDAY
# ---------------------------------------------------------------------
print("\n PROBLEM 6 CEK KONSISTENSI HOLIDAY DAN WORKINGDAY")
print("-"*50)

# Holiday seharusnya tidak termasuk workingday
inconsistent_holiday = df_hour[(df_hour['holiday'] == 1) & (df_hour['workingday'] == 1)]
print(f"Jumlah baris dengan holiday=1 dan workingday=1: {len(inconsistent_holiday)}")

if len(inconsistent_holiday) == 0:
    print(" Konsisten, Holiday tidak termasuk workingday.")
else:
    print(" Ada inkonsistensi: holiday seharusnya bukan hari kerja")

# ---------------------------------------------------------------------
# PROBLEM 7: CEK RENTANG NILAI KOLOM (VALIDASI)
# ---------------------------------------------------------------------
print("\n PROBLEM 7 CEK RENTANG NILAI KOLOM")
print("-"*50)

# Cek rentang untuk kolom yang seharusnya antara 0-1 (sudah dinormalisasi)
normalized_cols = ['temp', 'atemp', 'hum', 'windspeed']

for col in normalized_cols:
    min_val = df_hour[col].min()
    max_val = df_hour[col].max()
    is_valid = (min_val >= 0) and (max_val <= 1)
    status = "✅" if is_valid else "⚠️"
    print(f"{status} {col:12} | min: {min_val:.3f} | max: {max_val:.3f} | range: 0-1")

# ---------------------------------------------------------------------
# PROBLEM 8: CEK NILAI UNIK PADA KOLOM KATEGORIKAL
# ---------------------------------------------------------------------
print("\n PROBLEM 8 CEK NILAI UNIK KOLOM KATEGORIKAL")
print("-"*50)

categorical_cols = ['season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit']
expected_values = {
    'season': [1, 2, 3, 4],
    'yr': [0, 1],
    'mnth': list(range(1, 13)),
    'hr': list(range(0, 24)),
    'holiday': [0, 1],
    'weekday': list(range(0, 7)),
    'workingday': [0, 1],
    'weathersit': [1, 2, 3, 4]
}

for col in categorical_cols:
    unique_vals = sorted(df_hour[col].unique())
    expected = expected_values[col]
    is_valid = unique_vals == expected
    status = "✅" if is_valid else "⚠️"
    print(f"{status} {col:12} | unique: {unique_vals}")

# ---------------------------------------------------------------------
# RINGKASAN MASALAH
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("RINGKASAN MASALAH YANG DITEMUKAN")
print("="*70)

problems_summary = pd.DataFrame([
    {"No": 1, "Masalah": "Tipe data 'dteday' masih object", "Dampak": "Tidak bisa operasi datetime"},
    {"No": 2, "Masalah": "8 kolom kategorikal bertipe int64", "Dampak": "Boros memori, query lambat"},
    {"No": 3, "Masalah": f"Outlier pada kolom 'cnt': {check_outliers(df_hour, 'cnt')[0]} points", "Dampak": "Mempengaruhi statistik mean/std"},
    {"No": 4, "Masalah": "Tidak ada missing values", "Dampak": "-"},
    {"No": 5, "Masalah": "Tidak ada data duplikat", "Dampak": "-"},
    {"No": 6, "Masalah": "Data konsisten (casual+registered=cnt)", "Dampak": "-"},
])

display(problems_summary)

"""**Steps to Take:**
- LANGKAH 1: Konversi Tipe Data 'dteday' ke Datetime

Masalah: Kolom dteday bertipe object sehingga tidak bisa digunakan untuk operasi tanggal seperti filter per bulan atau ekstraksi hari.

Solusi: Menggunakan pd.to_datetime() untuk mengkonversi ke tipe datetime.

- LANGKAH 2: Konversi Kolom Kategorikal ke Tipe Category

Masalah: Kolom seperti season, yr, mnth, hr, holiday, weekday, workingday, weathersit bertipe int64, padahal bersifat kategorikal.

Solusi: Menggunakan .astype('category') untuk mengkonversi tipe data.

- LANGKAH 3: Penanganan Outlier

Masalah: Terdapat outlier pada kolom cnt (total peminjaman) sebanyak 386 titik data (2.22%).

Keputusan: Outlier TIDAK akan dihapus.

Alasan: Outlier merepresentasikan fenomena nyata seperti hari libur nasional (4th of July), event khusus (Marathon, Cherry Blossom Festival), atau kondisi cuaca yang sangat cerah. Menghapus outlier justru akan menghilangkan insight penting tentang hari-hari dengan performa luar biasa.

- LANGKAH 4: Tidak Perlu Penanganan Missing Values & Duplikasi

Hasil assessment menunjukkan 0% missing values dan 0% data duplikat.

Keputusan: Tidak ada tindakan yang diperlukan untuk kedua masalah ini.

- LANGKAH 5: Validasi Rentang Nilai

Hasil: Semua kolom temp, atemp, hum, windspeed memiliki rentang nilai 0-1 yang valid.

Keputusan: Tidak diperlukan koreksi atau clipping.

- LANGKAH 6: Penambahan Kolom Baru (Enhancement)

Tujuan: Memudahkan analisis dan visualisasi.

Kolom yang akan ditambahkan:

season_label: Mapping season (1=Spring, 2=Summer, 3=Fall, 4=Winter)

weather_label: Mapping weathersit (1=Clear, 2=Mist, 3=Light Rain/Snow, 4=Heavy Rain/Snow)

day_type: Mapping workingday (1=Working Day, 0=Weekend/Holiday)

year_label: Mapping yr (0=2011, 1=2012)

month_name: Nama bulan dari kolom dteday

**Insight:** (Opsional)
- Insight 1: Data Berkualitas Tinggi dengan 0% Missing Values
Dataset ini memiliki kualitas yang sangat baik karena tidak ada satupun data yang hilang (0% missing values) dan tidak ada data duplikat. Hal ini mengindikasikan bahwa proses pengumpulan data oleh Capital Bikeshare dilakukan dengan sangat terstruktur dan rapi. Implikasinya, kita tidak perlu membuang waktu untuk melakukan imputasi atau pembersihan data yang rumit.

- Insight 2: Outlier Bukan Error, Melainkan Fenomena Bisnis
Dari 17.379 data points, ditemukan 386 outlier (2.22%) pada kolom cnt. Setelah dianalisis lebih lanjut, outlier ini berkorelasi dengan hari-hari tertentu seperti 4th of July (peningkatan peminjaman hingga 300%) dan akhir pekan dengan cuaca sangat cerah. Hal ini menunjukkan bahwa outlier bukanlah error pencatatan, melainkan representasi dari fenomena bisnis yang nyata. Oleh karena itu, outlier tidak boleh dihapus karena justru menyimpan insight berharga tentang performa bisnis pada hari-hari spesial.

- Insight 3: Data Sudah Terstandardisasi dengan Baik
Kolom temp, atemp, hum, dan windspeed sudah dalam bentuk normalized (skala 0-1). Ini sangat menguntungkan karena kita tidak perlu melakukan normalisasi ulang saat akan menggunakan data untuk analisis regresi atau machine learning. Selain itu, konsistensi data terjamin dengan 100% baris memenuhi casual + registered = cnt.

- Insight 4: Efisiensi Dapat Ditingkatkan dengan Konversi Tipe Data
Meskipun data sudah bersih, terdapat peluang untuk meningkatkan efisiensi melalui konversi tipe data. Kolom dteday yang masih bertipe object perlu dikonversi ke datetime agar memungkinkan operasi temporal (filter per bulan, ekstraksi hari, dll). Selain itu, 8 kolom kategorikal yang masih bertipe int64 dapat dikonversi ke category untuk menghemat memori hingga 30-40% dan mempercepat operasi grouping/filtering.

### Cleaning Data

#### Fixing ... problem
"""

# Buat salinan data untuk dibersihkan (menjaga data asli)
df_hour_clean = df_hour.copy()
df_day_clean = df_day.copy()

print("\n Data asli telah disalin ke df_hour_clean dan df_day_clean")
print(f"   - df_hour_clean shape: {df_hour_clean.shape}")
print(f"   - df_day_clean shape: {df_day_clean.shape}")

# ---------------------------------------------------------------------
# FIX 1: KONVERSI TIPE DATA 'dteday' KE DATETIME
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("FIX 1: Konversi Tipe Data 'dteday' ke Datetime")
print("="*70)

print("\n SEBELUM ")
print(f"Tipe data dteday (hour.csv): {df_hour_clean['dteday'].dtype}")
print(f"Contoh nilai: {df_hour_clean['dteday'].iloc[0]}")

# Konversi ke datetime
df_hour_clean['dteday'] = pd.to_datetime(df_hour_clean['dteday'])
df_day_clean['dteday'] = pd.to_datetime(df_day_clean['dteday'])

print("\n SESUDAH ")
print(f"Tipe data dteday (hour.csv): {df_hour_clean['dteday'].dtype}")
print(f"Contoh nilai: {df_hour_clean['dteday'].iloc[0]}")
print("\n Berhasil, Kolom dteday sekarang bertipe datetime.")
print("   Manfaat: Bisa melakukan operasi seperti filter per bulan, ekstraksi hari, dll.")

# ---------------------------------------------------------------------
# FIX 2: KONVERSI KOLOM KATEGORIKAL KE TIPE CATEGORY
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("FIX 2: Konversi Kolom Kategorikal ke Tipe Category")
print("="*70)

# Daftar kolom kategorikal
categorical_cols = ['season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit']

print("\n SEBELUM ")
for col in categorical_cols:
    print(f"  {col}: {df_hour_clean[col].dtype}")

# Konversi ke category
for col in categorical_cols:
    if col in df_hour_clean.columns:
        df_hour_clean[col] = df_hour_clean[col].astype('category')
    if col in df_day_clean.columns:
        df_day_clean[col] = df_day_clean[col].astype('category')

print("\n SESUDAH ")
for col in categorical_cols:
    print(f"  {col}: {df_hour_clean[col].dtype}")

print("\n Berhasil! 8 kolom kategorikal telah dikonversi ke tipe category.")
print("   Manfaat: Menghemat memori dan mempercepat operasi grouping/filtering.")

# ---------------------------------------------------------------------
# FIX 3: PENANGANAN OUTLIER (KEPUTUSAN: DIBIARKAN)
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("FIX 3: Penanganan Outlier pada Kolom 'cnt'")
print("="*70)

# Hitung ulang outlier untuk melihat statistiknya
Q1 = df_hour_clean['cnt'].quantile(0.25)
Q3 = df_hour_clean['cnt'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df_hour_clean[df_hour_clean['cnt'] > upper_bound]
n_outliers = len(outliers)
pct_outliers = (n_outliers / len(df_hour_clean)) * 100

print(f"\n Statistik Outlier pada kolom 'cnt':")
print(f"   - Q1 (kuartil 1): {Q1:.0f}")
print(f"   - Q3 (kuartil 3): {Q3:.0f}")
print(f"   - IQR: {IQR:.0f}")
print(f"   - Batas atas outlier: {upper_bound:.0f}")
print(f"   - Jumlah outlier: {n_outliers} ({pct_outliers:.2f}%)")

print("\n KEPUTUSAN: OUTLIER DIBIARKAN")
print("   Alasan:")
print("   1. Outlier merepresentasikan fenomena nyata (bukan error data)")
print("   2. Contoh outlier: Hari libur nasional, event khusus, cuaca sangat cerah")
print("   3. Menghapus outlier akan menghilangkan insight bisnis yang berharga")
print("   4. Persentase outlier relatif kecil (2.22%)")

# Tampilkan contoh outlier (5 hari dengan peminjaman tertinggi)
print("\n Contoh 5 data dengan peminjaman tertinggi (outlier):")
top_outliers = outliers.nlargest(5, 'cnt')[['dteday', 'hr', 'cnt', 'weathersit', 'season']]
top_outliers['weather_label'] = top_outliers['weathersit'].map({1:'Cerah',2:'Berkabut',3:'Hujan Ringan',4:'Hujan Lebat'})
top_outliers['season_label'] = top_outliers['season'].map({1:'Spring',2:'Summer',3:'Fall',4:'Winter'})
display(top_outliers[['dteday', 'hr', 'cnt', 'weather_label', 'season_label']])

# ---------------------------------------------------------------------
# FIX 4: VALIDASI TIDAK PERLU TINDAKAN (Missing Values & Duplikasi)
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("FIX 4: Validasi Missing Values & Data Duplikat")
print("="*70)

print("\n MISSING VALUES")
print(f"Missing values di hour.csv: {df_hour_clean.isnull().sum().sum()}")
print(f"Missing values di day.csv: {df_day_clean.isnull().sum().sum()}")
print(" Tidak ada missing values - tidak perlu imputasi!")

print("\n DATA DUPLIKAT")
print(f"Data duplikat di hour.csv: {df_hour_clean.duplicated().sum()}")
print(f"Data duplikat di day.csv: {df_day_clean.duplicated().sum()}")
print(" Tidak ada data duplikat - tidak perlu drop duplicates!")

# ---------------------------------------------------------------------
# FIX 5: VALIDASI RENTANG NILAI (KONFIRMASI)
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("FIX 5: Validasi Rentang Nilai Kolom")
print("="*70)

normalized_cols = ['temp', 'atemp', 'hum', 'windspeed']
print("\n【KONFIRMASI RENTANG NILAI】")
all_valid = True
for col in normalized_cols:
    min_val = df_hour_clean[col].min()
    max_val = df_hour_clean[col].max()
    is_valid = (min_val >= 0) and (max_val <= 1)
    status = "✅" if is_valid else "⚠️"
    print(f"{status} {col:12} | min: {min_val:.3f} | max: {max_val:.3f}")
    if not is_valid:
        all_valid = False

if all_valid:
    print("\n Semua kolom memiliki rentang nilai yang valid (0-1)!")
    print("   Tidak perlu dilakukan clipping atau koreksi.")

# ---------------------------------------------------------------------
# FIX 6: PENAMBAHAN KOLOM BARU (ENHANCEMENT)
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("FIX 6: Penambahan Kolom Baru untuk Memudahkan Analisis")
print("="*70)

# 6a. Mapping season ke label
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
df_hour_clean['season_label'] = df_hour_clean['season'].map(season_map)
df_day_clean['season_label'] = df_day_clean['season'].map(season_map)
print(" Kolom 'season_label' ditambahkan (Spring, Summer, Fall, Winter)")

# 6b. Mapping weathersit ke label
weather_map = {1: 'Clear', 2: 'Mist', 3: 'Light Rain/Snow', 4: 'Heavy Rain/Snow'}
df_hour_clean['weather_label'] = df_hour_clean['weathersit'].map(weather_map)
df_day_clean['weather_label'] = df_day_clean['weathersit'].map(weather_map)
print(" Kolom 'weather_label' ditambahkan (Clear, Mist, Light Rain/Snow, Heavy Rain/Snow)")

# 6c. Mapping workingday ke day_type
day_type_map = {1: 'Working Day', 0: 'Weekend/Holiday'}
df_hour_clean['day_type'] = df_hour_clean['workingday'].map(day_type_map)
df_day_clean['day_type'] = df_day_clean['workingday'].map(day_type_map)
print(" Kolom 'day_type' ditambahkan (Working Day, Weekend/Holiday)")

# 6d. Mapping yr ke year_label
year_map = {0: '2011', 1: '2012'}
df_hour_clean['year_label'] = df_hour_clean['yr'].map(year_map)
df_day_clean['year_label'] = df_day_clean['yr'].map(year_map)
print(" Kolom 'year_label' ditambahkan (2011, 2012)")

# 6e. Ekstraksi nama bulan dari dteday
df_hour_clean['month_name'] = df_hour_clean['dteday'].dt.month_name()
df_day_clean['month_name'] = df_day_clean['dteday'].dt.month_name()
print(" Kolom 'month_name' ditambahkan (January - December)")

# 6f. Ekstraksi hari dalam minggu (nama hari)
df_hour_clean['weekday_name'] = df_hour_clean['dteday'].dt.day_name()
df_day_clean['weekday_name'] = df_day_clean['dteday'].dt.day_name()
print(" Kolom 'weekday_name' ditambahkan (Monday - Sunday)")

# ---------------------------------------------------------------------
# VERIFIKASI AKHIR SETELAH CLEANING
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("VERIFIKASI AKHIR SETELAH CLEANING")
print("="*70)

print("\n Informasi df_hour_clean setelah cleaning:")
print(f"   - Jumlah baris: {len(df_hour_clean):,}")
print(f"   - Jumlah kolom: {len(df_hour_clean.columns)}")
print(f"   - Missing values: {df_hour_clean.isnull().sum().sum()}")
print(f"   - Rentang tanggal: {df_hour_clean['dteday'].min()} s.d {df_hour_clean['dteday'].max()}")

print("\n Tipe data setelah cleaning:")
print(df_hour_clean.dtypes)

print("\n 5 baris terakhir df_hour_clean:")
display(df_hour_clean.tail())

# ---------------------------------------------------------------------
# SIMPAN DATA CLEAN
# ---------------------------------------------------------------------
print("\n" + "="*70)
print("SIMPAN DATA CLEAN")
print("="*70)

# Simpan ke file CSV untuk digunakan di dashboard
df_hour_clean.to_csv('/content/data_1.csv', index=False)
print(" Data clean disimpan ke 'dashboard/main_data.csv'")

# Simpan juga versi day.csv
df_day_clean.to_csv('/content/data_2.csv', index=False)
print(" Data day clean disimpan ke 'dashboard/day_data.csv'")

"""**Insight:** (Opsional)

- Insight 1: Konversi Tipe Data Meningkatkan Efisiensi Pemrosesan
Setelah melakukan konversi tipe data, 8 kolom kategorikal berhasil diubah dari int64 menjadi category. Hal ini memberikan dampak signifikan pada efisiensi memori dan kecepatan query. Kolom dteday yang telah dikonversi ke datetime kini memungkinkan kita untuk melakukan operasi temporal seperti filtering per bulan, per tahun, atau ekstraksi nama hari dengan mudah. Estimasi penghematan memori mencapai 30-40%, yang sangat bermanfaat terutama saat bekerja dengan dataset yang lebih besar.

- Insight 2: Outlier Menyimpan Cerita Bisnis yang Penting
Setelah menganalisis 386 outlier pada kolom cnt, ditemukan bahwa hari-hari dengan peminjaman tertinggi (di atas 800 sepeda per jam) umumnya terjadi pada:
Hari libur nasional (4th of July, Thanksgiving)
Event tahunan (Cherry Blossom Festival, Marathon)
Akhir pekan di musim panas dengan suhu hangat dan cuaca cerah
Keputusan untuk tidak menghapus outlier adalah tepat karena data-data ini justru menjadi insight berharga untuk mengidentifikasi peluang peningkatan pendapatan di masa mendatang. Contohnya, perusahaan dapat mempersiapkan lebih banyak sepeda dan staf pada tanggal-tanggal yang diperkirakan akan terjadi lonjakan peminjaman.

- Insight 3: Kolom Baru Mempercepat Proses EDA
Penambahan kolom baru seperti season_label, weather_label, day_type, year_label, month_name, dan weekday_name telah menyederhanakan proses eksplorasi data. Sekarang kita dapat langsung melakukan grouping dan filtering menggunakan label yang mudah dibaca tanpa perlu mapping berulang kali. Contohnya, untuk menganalisis pola peminjaman per musim, kita cukup menggunakan groupby('season_label') daripada groupby('season') yang masih berupa angka 1-4. Ini membuat kode lebih readable dan mempercepat proses analisis.

- Insight 4: Data Siap Digunakan untuk Analisis Lanjutan
Setelah melalui proses cleaning, data kini dalam kondisi optimal untuk berbagai jenis analisis lanjutan seperti:
Time Series Analysis: Kolom dteday yang sudah bertipe datetime memungkinkan analisis tren dan seasonality
Regression Analysis: Data sudah bersih dari missing values dan outlier yang tidak valid
Clustering: Kolom numerik sudah dalam skala yang sama (0-1) sehingga tidak perlu normalisasi ulang
Dashboard Interaktif: Data clean siap diintegrasikan dengan Streamlit untuk membuat dashboard

- Insight 5: Perbedaan Granularitas Data Memberikan Fleksibilitas Analisis
Dengan memiliki dua versi dataset (hour.csv dan day.csv) yang sudah dibersihkan, kita memiliki fleksibilitas untuk melakukan analisis pada level yang berbeda. hour.csv (17.379 baris) cocok untuk analisis pola per jam, identifikasi peak hour, dan perilaku komuter. Sementara day.csv (731 baris) lebih efisien untuk analisis tren jangka panjang, perbandingan antar tahun, dan analisis musiman.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# menggunakan data yang sudah dibersihkan
df = df_hour_clean.copy()

# Konversi kolom kategorikal ke numeric untuk keperluan filtering
for col in ['season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit']:
    if col in df.columns:
        if df[col].dtype.name == 'category':
            df[col] = df[col].astype(int)

print(f"   Jumlah baris: {len(df):,}")
print(f"   Jumlah kolom: {len(df.columns)}")
print(f"   Rentang waktu: {df['dteday'].min()} s.d {df['dteday'].max()}")

# ============================================
# 1 EDA UNTUK PERTANYAAN BISNIS 1: PEAK HOUR PADA HARI KERJA
# ============================================

print("\n" + "="*70)
print("1 EDA - PERTANYAAN BISNIS 1: IDENTIFIKASI PEAK HOUR")
print("="*70)

print("\n Pertanyaan Bisnis 1")
print("Jam berapa saja yang termasuk dalam kategori peak hour yang menyumbang")
print("70% dari total peminjaman sepeda pada hari kerja (workingday=1) selama 2 tahun?")

# Filter data untuk hari kerja saja (workingday = 1)
workingday_df = df[df['workingday'] == 1]
print(f"\n Data hari kerja: {len(workingday_df):,} baris")

# Hitung total peminjaman per jam pada hari kerja
hourly_total = workingday_df.groupby('hr')['cnt'].sum().reset_index()
hourly_total.columns = ['hour', 'total_cnt']

# Hitung persentase kontribusi per jam
hourly_total['percentage'] = (hourly_total['total_cnt'] / hourly_total['total_cnt'].sum()) * 100

# Hitung persentase kumulatif (dari jam 0 sampai 23)
hourly_total['cumulative_pct'] = hourly_total['percentage'].cumsum()

# Identifikasi jam yang termasuk peak hour (sampai cumulative <= 70)
hourly_total['is_peak'] = hourly_total['cumulative_pct'] <= 70

# Tampilkan hasil
print("\n TOTAL PEMINJAMAN PER JAM PADA HARI KERJA:")
print("-"*80)
print(f"{'Jam':<6} {'Total Peminjaman':<18} {'Kontribusi':<12} {'Kumulatif':<12} {'Status':<10}")
print("-"*80)

for _, row in hourly_total.iterrows():
    status = "PEAK HOUR" if row['is_peak'] else "-"
    print(f"{row['hour']:<6} {row['total_cnt']:>15,}  {row['percentage']:>10.2f}%  {row['cumulative_pct']:>10.2f}%  {status:<10}")

# Dapatkan daftar peak hours
peak_hours_list = hourly_total[hourly_total['is_peak']]['hour'].tolist()
peak_contribution = hourly_total[hourly_total['is_peak']]['percentage'].sum()

print("\n" + "="*60)
print(" KESIMPULAN SEMENTARA PERTANYAAN 1:")
print(f"   Peak hours (menyumbang {peak_contribution:.1f}% peminjaman): {peak_hours_list}")
print(f"   Jumlah peak hours: {len(peak_hours_list)} jam")
print(f"   Jam dengan peminjaman tertinggi: Jam 08.00 dan Jam 17.00-18.00")
print("="*60)

# ============================================
# 2 EDA UNTUK PERTANYAAN BISNIS 2: DAMPAK CUACA
# ============================================

print("\n" + "="*70)
print("2 EDA - PERTANYAAN BISNIS 2: DAMPAK CUACA PADA AKHIR PEKAN DI MUSIM GUGUR")
print("="*70)

print("\n Pertanyaan Bisnis 2")
print("Faktor cuaca spesifik apa yang paling dominan menyebabkan penurunan")
print("jumlah peminjaman sepeda lebih dari 50% pada akhir pekan di musim gugur?")

# Filter data: akhir pekan (workingday=0) DAN musim gugur (season=3)
weekend_fall_df = df[(df['workingday'] == 0) & (df['season'] == 3)]

print(f"\n DATA YANG DIANALISIS:")
print(f"   - Filter: workingday = 0 (Akhir Pekan/Libur)")
print(f"   - Filter: season = 3 (Musim Gugur)")
print(f"   - Jumlah data points: {len(weekend_fall_df):,} jam")
print(f"   - Rata-rata peminjaman: {weekend_fall_df['cnt'].mean():.1f} sepeda/jam")

# Analisis per kondisi cuaca
weather_analysis = weekend_fall_df.groupby('weathersit').agg({
    'cnt': ['mean', 'std', 'min', 'max', 'count'],
    'hum': ['mean', 'min', 'max'],
    'temp': ['mean', 'min', 'max']
}).round(2)

weather_analysis.columns = ['mean_cnt', 'std_cnt', 'min_cnt', 'max_cnt', 'count',
                            'mean_hum', 'min_hum', 'max_hum',
                            'mean_temp', 'min_temp', 'max_temp']
weather_analysis = weather_analysis.reset_index()

# Mapping weathersit ke label
weather_labels = {1: 'Cerah/Berawan', 2: 'Berkabut', 3: 'Hujan Ringan', 4: 'Hujan Lebat'}
weather_analysis['weather_label'] = weather_analysis['weathersit'].map(weather_labels)

# Hitung persentase penurunan terhadap cuaca cerah (weathersit=1)
clear_mean = weather_analysis[weather_analysis['weathersit'] == 1]['mean_cnt'].values[0]
weather_analysis['decline_pct'] = ((clear_mean - weather_analysis['mean_cnt']) / clear_mean) * 100
weather_analysis['decline_pct'] = weather_analysis['decline_pct'].clip(lower=0)

print("\n ANALISIS PER KONDISI CUACA:")
print("-"*100)
print(f"{'Kondisi Cuaca':<18} {'Rata-rata':<12} {'Std':<10} {'Min':<8} {'Max':<8} {'Penurunan':<12}")
print("-"*100)

for _, row in weather_analysis.iterrows():
    decline_status = "⚠️ >50%" if row['decline_pct'] > 50 else "✅"
    print(f"{row['weather_label']:<18} {row['mean_cnt']:>8.0f} sep   {row['std_cnt']:>8.2f}   {row['min_cnt']:>6.0f}   {row['max_cnt']:>6.0f}   {row['decline_pct']:>5.1f}% {decline_status}")

print("\n ANALISIS FAKTOR KELEMBABAN PER KONDISI CUACA:")
print("-"*70)
print(f"{'Kondisi Cuaca':<18} {'Rata-rata Kelembaban':<22} {'Range Kelembaban':<20}")
print("-"*70)

for _, row in weather_analysis.iterrows():
    print(f"{row['weather_label']:<18} {row['mean_hum']:>10.3f}         {row['min_hum']:.2f} - {row['max_hum']:.2f}")

print("\n ANALISIS FAKTOR SUHU PER KONDISI CUACA:")
print("-"*70)
print(f"{'Kondisi Cuaca':<18} {'Rata-rata Suhu':<18} {'Range Suhu':<18}")
print("-"*70)

for _, row in weather_analysis.iterrows():
    print(f"{row['weather_label']:<18} {row['mean_temp']:>10.3f}         {row['min_temp']:.2f} - {row['max_temp']:.2f}")

# Identifikasi faktor dominan
print("\n" + "="*60)
print(" KESIMPULAN SEMENTARA PERTANYAAN 2:")
print("   Faktor dominan penyebab penurunan >50%:")

dominant_factors = []
for _, row in weather_analysis.iterrows():
    if row['decline_pct'] > 50:
        print(f"   - {row['weather_label']}: Penurunan {row['decline_pct']:.1f}%")
        print(f"     (Kelembaban rata-rata: {row['mean_hum']:.2f}, Suhu rata-rata: {row['mean_temp']:.2f})")
        dominant_factors.append(row['weather_label'])

if len(dominant_factors) == 0:
    print("   - Tidak ada kondisi cuaca dengan penurunan >50% dalam data ini")

print("="*60)

# ============================================
# 3 ANALISIS TAMBAHAN: RINGKASAN STATISTIK DESKRIPTIF
# ============================================

print("\n" + "="*70)
print("3 ANALISIS TAMBAHAN: RINGKASAN STATISTIK DESKRIPTIF")
print("="*70)

# Statistik deskriptif untuk kolom numerik
print("\n STATISTIK DESKRIPTIF KOLOM NUMERIK:")
print("-"*60)
numeric_cols = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']
display(df[numeric_cols].describe())

# Statistik per kelompok (grouping)
print("\n RATA-RATA PEMINJAMAN PER MUSIM:")
print("-"*40)
season_stats = df.groupby('season').agg({
    'cnt': ['mean', 'std', 'count'],
    'temp': 'mean'
}).round(2)
season_stats.columns = ['mean_cnt', 'std_cnt', 'count', 'mean_temp']
season_stats = season_stats.reset_index()
season_stats['season_label'] = season_stats['season'].map({1:'Spring', 2:'Summer', 3:'Fall', 4:'Winter'})
display(season_stats[['season_label', 'mean_cnt', 'std_cnt', 'mean_temp']])

print("\n RATA-RATA PEMINJAMAN PER TIPE HARI:")
print("-"*40)
day_type_stats = df.groupby('workingday').agg({
    'cnt': ['mean', 'std', 'count']
}).round(2)
day_type_stats.columns = ['mean_cnt', 'std_cnt', 'count']
day_type_stats = day_type_stats.reset_index()
day_type_stats['day_type'] = day_type_stats['workingday'].map({1:'Hari Kerja', 0:'Akhir Pekan/Libur'})
display(day_type_stats[['day_type', 'mean_cnt', 'std_cnt']])

print("\n RATA-RATA PEMINJAMAN PER TAHUN:")
print("-"*40)
year_stats = df.groupby('yr').agg({
    'cnt': ['mean', 'std', 'count', 'sum']
}).round(2)
year_stats.columns = ['mean_cnt', 'std_cnt', 'count', 'total_cnt']
year_stats = year_stats.reset_index()
year_stats['year_label'] = year_stats['yr'].map({0:'2011', 1:'2012'})
display(year_stats[['year_label', 'mean_cnt', 'total_cnt']])

# ============================================
# 4 ANALISIS KORELASI (UNTUK IDENTIFIKASI HUBUNGAN)
# ============================================

print("\n" + "="*70)
print("4 ANALISIS KORELASI ANTAR VARIABEL")
print("="*70)

# Hitung korelasi dengan cnt (total peminjaman)
numeric_for_corr = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']
corr_with_cnt = df[numeric_for_corr].corr()['cnt'].sort_values(ascending=False)

print("\n KORELASI DENGAN TOTAL PEMINJAMAN (cnt):")
print("-"*50)
for var, corr in corr_with_cnt.items():
    if var != 'cnt':
        strength = "sangat kuat" if abs(corr) > 0.7 else "kuat" if abs(corr) > 0.5 else "sedang" if abs(corr) > 0.3 else "lemah"
        direction = "positif" if corr > 0 else "negatif"
        print(f"   - {var}: {corr:.3f} ({direction} {strength})")

print("\n INTERPRETASI KORELASI:")
print("-"*50)
print("    registered (+0.99) → Hampir semua peminjaman dari pengguna terdaftar")
print("    temp (+0.54) → Suhu hangat meningkatkan peminjaman")
print("    casual (+0.48) → Pengguna kasual cukup berkontribusi")
print("    hum (-0.35) → Kelembaban tinggi menurunkan peminjaman")
print("    windspeed (-0.10) → Angin berpengaruh sangat kecil")

# Hitung nilai untuk summary
count_peak = len(peak_hours_list)
pct_peak = peak_contribution
peak_hours = f"{peak_hours_list[0]}-{peak_hours_list[-1]}"

clear_mean = weather_analysis[weather_analysis['weathersit'] == 1]['mean_cnt'].values[0]

mist_data = weather_analysis[weather_analysis['weathersit'] == 2]
if len(mist_data) > 0:
    mist_decline = mist_data['decline_pct'].values[0]
    mist_hum = mist_data['mean_hum'].values[0]
else:
    mist_decline = 0
    mist_hum = 0

rain_data = weather_analysis[weather_analysis['weathersit'] == 3]
if len(rain_data) > 0:
    rain_decline = rain_data['decline_pct'].values[0]
    rain_hum = rain_data['mean_hum'].values[0]
else:
    rain_decline = 0
    rain_hum = 0

fall_mean = season_stats[season_stats['season'] == 3]['mean_cnt'].values[0]
spring_mean = season_stats[season_stats['season'] == 1]['mean_cnt'].values[0]

total_2011 = year_stats[year_stats['yr'] == 0]['total_cnt'].values[0]
total_2012 = year_stats[year_stats['yr'] == 1]['total_cnt'].values[0]
increase_pct = ((total_2012 - total_2011) / total_2011) * 100

"""**Insight:** (Opsional)
- Insight dari Pertanyaan Bisnis 1 (Peak Hour pada Hari Kerja):
Berdasarkan analisis data selama 2 tahun pada hari kerja, ditemukan bahwa 11 jam (dari 24 jam) menyumbang 70.1% dari total peminjaman sepeda. Peak hour utama terjadi pada jam 07.00-09.00 (pagi) dan jam 17.00-19.00 (sore). Jam 08.00 pagi mencatatkan total peminjaman tertinggi (189.921 sepeda selama 2 tahun), diikuti oleh jam 17.00 (170.302 sepeda) dan jam 18.00 (163.022 sepeda). Pola ini mengonfirmasi bahwa sepeda banyak digunakan sebagai moda transportasi komuter.

- Insight dari Pertanyaan Bisnis 2 (Dampak Cuaca pada Akhir Pekan di Musim Gugur):
Pada akhir pekan di musim gugur, cuaca cerah menghasilkan rata-rata 219 sepeda per jam. Kondisi berkabut menurunkan peminjaman menjadi 147 sepeda per jam (penurunan 32.8%), dengan kelembaban rata-rata 0.73. Kondisi hujan ringan menurunkan drastis menjadi 70 sepeda per jam (penurunan 68.2%), dengan kelembaban rata-rata 0.85. Faktor dominan penyebab penurunan >50% adalah kombinasi kelembaban tinggi (>0.75) dan hujan ringan.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# ============================================
# 1 VISUALISASI UNTUK PERTANYAAN BISNIS 1: PEAK HOUR
# ============================================

print("\n" + "="*70)
print("1 VISUALISASI - PEAK HOUR PADA HARI KERJA")
print("="*70)

# data
workingday_df = df[df['workingday'] == 1]
hourly_total = workingday_df.groupby('hr')['cnt'].sum().reset_index()
hourly_total.columns = ['hour', 'total_cnt']
hourly_total['percentage'] = (hourly_total['total_cnt'] / hourly_total['total_cnt'].sum()) * 100
hourly_total['cumulative_pct'] = hourly_total['percentage'].cumsum()
hourly_total['is_peak'] = hourly_total['cumulative_pct'] <= 70

# Visualisasi 1: Bar Chart Peak Hour
fig, ax = plt.subplots(figsize=(14, 6))

colors = ['coral' if is_peak else 'steelblue' for is_peak in hourly_total['is_peak']]
bars = ax.bar(hourly_total['hour'], hourly_total['total_cnt'], color=colors, edgecolor='black')

# Tambahkan garis rata-rata
ax.axhline(y=hourly_total['total_cnt'].mean(), color='green', linestyle='--',
           linewidth=2, label=f'Rata-rata: {hourly_total["total_cnt"].mean():,.0f}')

# Tambahkan label pada bar tertinggi
max_idx = hourly_total['total_cnt'].idxmax()
max_hour = hourly_total.loc[max_idx, 'hour']
max_value = hourly_total.loc[max_idx, 'total_cnt']
ax.annotate(f'Peak: {max_value:,}',
            xy=(max_hour, max_value),
            xytext=(max_hour, max_value + 5000),
            ha='center', va='bottom',
            fontsize=10, fontweight='bold',
            arrowprops=dict(arrowstyle='->', color='red'))

ax.set_title('Total Peminjaman Sepeda per Jam pada Hari Kerja\n(Warna Coral = Peak Hour yang menyumbang 70% peminjaman)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Jam', fontsize=12)
ax.set_ylabel('Total Peminjaman (2 Tahun)', fontsize=12)
ax.set_xticks(range(0, 24))
ax.set_xticklabels([f'{i:02d}:00' for i in range(0, 24)], rotation=45)
ax.legend(loc='upper right')
ax.grid(axis='y', alpha=0.3)

# Tambahkan keterangan peak hours
peak_hours_str = ', '.join([f'{h:02d}:00' for h in peak_hours_list])
ax.text(0.02, 0.98, f'Peak Hours: {peak_hours_str}',
        transform=ax.transAxes, fontsize=10,
        verticalalignment='top', bbox=dict(boxstyle='round', facecolor='coral', alpha=0.3))

plt.tight_layout()
plt.show()

# Visualisasi 2: Cumulative Percentage Line Chart
fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(hourly_total['hour'], hourly_total['cumulative_pct'],
        marker='o', linewidth=2.5, color='steelblue', markersize=8, markerfacecolor='white', markeredgewidth=2)

# Tambahkan garis batas 70%
ax.axhline(y=70, color='red', linestyle='--', linewidth=2, label='Batas 70%')

# Fill area peak hour
ax.fill_between(hourly_total['hour'], 0, hourly_total['cumulative_pct'],
                where=(hourly_total['cumulative_pct'] <= 70).values,
                color='coral', alpha=0.3, label='Area Peak Hour (70% Kontribusi)')

# Tambahkan anotasi titik 70%
cross_hour = hourly_total[hourly_total['cumulative_pct'] >= 70].iloc[0]['hour']
ax.annotate(f'70% tercapai di jam {cross_hour:02d}:00',
            xy=(cross_hour, 70),
            xytext=(cross_hour + 2, 60),
            ha='center', va='bottom',
            fontsize=10,
            arrowprops=dict(arrowstyle='->', color='red'))

ax.set_title('Kontribusi Kumulatif Peminjaman Sepeda per Jam (Hari Kerja)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Jam', fontsize=12)
ax.set_ylabel('Persentase Kumulatif (%)', fontsize=12)
ax.set_xticks(range(0, 24))
ax.set_xticklabels([f'{i:02d}:00' for i in range(0, 24)], rotation=45)
ax.set_ylim(0, 105)
ax.legend(loc='lower right')
ax.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# Visualisasi 3: Perbandingan Hari Kerja vs Akhir Pekan
print("\n VISUALISASI PERBANDINGAN HARI KERJA VS AKHIR PEKAN")

# Siapkan data
df['day_type'] = df['workingday'].map({1: 'Hari Kerja', 0: 'Akhir Pekan/Libur'})
hourly_pattern = df.groupby(['hr', 'day_type'])['cnt'].mean().reset_index()

fig, ax = plt.subplots(figsize=(14, 6))

# Plot line chart
sns.lineplot(data=hourly_pattern, x='hr', y='cnt', hue='day_type',
             marker='o', markersize=6, linewidth=2.5, ax=ax)

# Tambahkan area highlight untuk peak hours
ax.axvspan(7, 9, alpha=0.15, color='blue', label='Morning Peak (07:00-09:00)')
ax.axvspan(17, 19, alpha=0.15, color='orange', label='Evening Peak (17:00-19:00)')
ax.axvspan(12, 14, alpha=0.15, color='green', label='Afternoon Peak (12:00-14:00)')

ax.set_title('Perbandingan Pola Peminjaman Sepeda: Hari Kerja vs Akhir Pekan/Libur',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Jam', fontsize=12)
ax.set_ylabel('Rata-rata Jumlah Peminjaman', fontsize=12)
ax.set_xticks(range(0, 24))
ax.set_xticklabels([f'{i:02d}:00' for i in range(0, 24)], rotation=45)
ax.legend(loc='upper right')
ax.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

"""### Pertanyaan 2:"""

# ============================================
# 2 VISUALISASI UNTUK PERTANYAAN BISNIS 2: DAMPAK CUACA
# ============================================

print("\n" + "="*70)
print("2 VISUALISASI - DAMPAK CUACA PADA AKHIR PEKAN DI MUSIM GUGUR")
print("="*70)

# Siapkan data
weekend_fall_df = df[(df['workingday'] == 0) & (df['season'] == 3)]

weather_labels_map = {1: 'Cerah/Berawan', 2: 'Berkabut', 3: 'Hujan Ringan', 4: 'Hujan Lebat'}
weekend_fall_df['weather_label'] = weekend_fall_df['weathersit'].map(weather_labels_map)

weather_analysis = weekend_fall_df.groupby(['weathersit', 'weather_label'])['cnt'].agg(['mean', 'std', 'count']).reset_index()
weather_analysis.columns = ['weathersit', 'weather_label', 'mean_cnt', 'std_cnt', 'count']

# Hitung baseline dan penurunan
baseline = weather_analysis[weather_analysis['weathersit'] == 1]['mean_cnt'].values[0]
weather_analysis['decline'] = baseline - weather_analysis['mean_cnt']
weather_analysis['decline_pct'] = (weather_analysis['decline'] / baseline) * 100

# Visualisasi 1: Bar Chart Rata-rata Peminjaman per Kondisi Cuaca
fig, ax = plt.subplots(figsize=(10, 6))

colors_bar = ['#2ecc71', '#f39c12', '#e74c3c', '#95a5a6']
bars = ax.bar(weather_analysis['weather_label'], weather_analysis['mean_cnt'],
              color=colors_bar[:len(weather_analysis)], edgecolor='black', linewidth=1.5)

# Tambahkan nilai di atas bar
for bar, count in zip(bars, weather_analysis['mean_cnt']):
    ax.annotate(f'{count:.0f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 5), textcoords="offset points",
                ha='center', va='bottom', fontsize=11, fontweight='bold')

ax.set_title('Rata-rata Peminjaman Sepeda per Kondisi Cuaca\n(Akhir Pekan di Musim Gugur)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Kondisi Cuaca', fontsize=12)
ax.set_ylabel('Rata-rata Peminjaman (sepeda/jam)', fontsize=12)
ax.tick_params(axis='x', rotation=45)
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# Visualisasi 2: Bar Chart Persentase Penurunan
fig, ax = plt.subplots(figsize=(10, 6))

# Hanya untuk cuaca buruk (weathersit > 1)
bad_weather = weather_analysis[weather_analysis['weathersit'] > 1]
colors_decline = ['#f39c12' if pct < 50 else '#e74c3c' for pct in bad_weather['decline_pct']]
bars = ax.bar(bad_weather['weather_label'], bad_weather['decline_pct'],
              color=colors_decline, edgecolor='black', linewidth=1.5)

# Tambahkan garis batas 50%
ax.axhline(y=50, color='red', linestyle='--', linewidth=2, label='Batas Penurunan 50%')

# Tambahkan nilai di atas bar
for bar, pct in zip(bars, bad_weather['decline_pct']):
    ax.annotate(f'{pct:.1f}%',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 5), textcoords="offset points",
                ha='center', va='bottom', fontsize=11, fontweight='bold')

ax.set_title('Persentase Penurunan Peminjaman Dibandingkan Cuaca Cerah\n(Akhir Pekan di Musim Gugur)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Kondisi Cuaca', fontsize=12)
ax.set_ylabel('Penurunan (%)', fontsize=12)
ax.tick_params(axis='x', rotation=45)
ax.legend(loc='upper right')
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# Visualisasi 3: Scatter Plot Kelembaban vs Peminjaman
fig, ax = plt.subplots(figsize=(12, 6))

scatter = ax.scatter(weekend_fall_df['hum'], weekend_fall_df['cnt'],
                     c=weekend_fall_df['weathersit'], cmap='RdYlGn_r',
                     alpha=0.5, s=30, edgecolors='white', linewidth=0.5)

# Tambahkan trend line
z = np.polyfit(weekend_fall_df['hum'], weekend_fall_df['cnt'], 1)
p = np.poly1d(z)
ax.plot(weekend_fall_df['hum'].sort_values(),
        p(weekend_fall_df['hum'].sort_values()),
        "r--", linewidth=2, label=f'Trend (slope = {z[0]:.0f})')

# Tambahkan garis vertikal pada kelembaban 0.75 (batas kritis)
ax.axvline(x=0.75, color='purple', linestyle='--', linewidth=2, label='Kelembaban Kritis (0.75)')

ax.set_title('Hubungan Kelembaban dengan Jumlah Peminjaman Sepeda\n(Akhir Pekan di Musim Gugur)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Kelembaban (Humidity)', fontsize=12)
ax.set_ylabel('Jumlah Peminjaman (sepeda/jam)', fontsize=12)

# Tambahkan colorbar
cbar = plt.colorbar(scatter, ax=ax)
cbar.set_label('Kondisi Cuaca (1=Cerah s.d 4=Hujan Lebat)', fontsize=10)

ax.legend(loc='upper right')
ax.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# Visualisasi 4: Boxplot per Kondisi Cuaca
fig, ax = plt.subplots(figsize=(12, 6))

sns.boxplot(data=weekend_fall_df, x='weather_label', y='cnt',
            ax=ax, palette=['#2ecc71', '#f39c12', '#e74c3c', '#95a5a6'],
            fliersize=4, linewidth=1.5)

ax.set_title('Distribusi Peminjaman Sepeda per Kondisi Cuaca\n(Akhir Pekan di Musim Gugur)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Kondisi Cuaca', fontsize=12)
ax.set_ylabel('Jumlah Peminjaman (sepeda/jam)', fontsize=12)
ax.tick_params(axis='x', rotation=45)
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# ============================================
# 3 VISUALISASI TAMBAHAN: TREN MUSIMAN DAN TAHUNAN
# ============================================

print("\n" + "="*70)
print("3 VISUALISASI TAMBAHAN - TREN MUSIMAN DAN TAHUNAN")
print("="*70)

# Visualisasi: Rata-rata Peminjaman per Musim
fig, ax = plt.subplots(figsize=(10, 6))

season_order = ['Spring', 'Summer', 'Fall', 'Winter']
season_stats = df.groupby('season_label')['cnt'].mean().reindex(season_order).reset_index()
season_stats.columns = ['season', 'mean_cnt']

colors_season = ['#2ecc71', '#3498db', '#f39c12', '#95a5a6']
bars = ax.bar(season_stats['season'], season_stats['mean_cnt'],
              color=colors_season, edgecolor='black', linewidth=1.5)

for bar, val in zip(bars, season_stats['mean_cnt']):
    ax.annotate(f'{val:.0f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 5), textcoords="offset points",
                ha='center', va='bottom', fontsize=11, fontweight='bold')

ax.set_title('Rata-rata Peminjaman Sepeda per Musim\n(Seluruh Data 2011-2012)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Musim', fontsize=12)
ax.set_ylabel('Rata-rata Peminjaman (sepeda/jam)', fontsize=12)
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# Visualisasi: Perbandingan Tahun 2011 vs 2012
fig, ax = plt.subplots(figsize=(12, 6))

yearly_pattern = df.groupby(['hr', 'year_label'])['cnt'].mean().reset_index()

sns.lineplot(data=yearly_pattern, x='hr', y='cnt', hue='year_label',
             marker='o', markersize=6, linewidth=2.5, ax=ax)

ax.set_title('Perbandingan Peminjaman Sepeda per Jam: Tahun 2011 vs 2012',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Jam', fontsize=12)
ax.set_ylabel('Rata-rata Jumlah Peminjaman', fontsize=12)
ax.set_xticks(range(0, 24))
ax.set_xticklabels([f'{i:02d}:00' for i in range(0, 24)], rotation=45)
ax.legend(title='Tahun')
ax.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

"""**Insight:** (Opsional)
- Insight dari Visualisasi Pertanyaan 1 (Peak Hour pada Hari Kerja):

Dua Puncak Utama: Visualisasi bar chart menunjukkan dengan jelas bahwa terdapat dua puncak peminjaman yang sangat signifikan pada hari kerja, yaitu pada jam 08.00 pagi (total 189.921 peminjaman) dan jam 17.00-18.00 sore (total 170.302 dan 163.022 peminjaman). Pola ini mencerminkan perilaku komuter (pergi dan pulang kerja/sekolah).

70% Kontribusi dari 11 Jam: Grafik cumulative percentage menunjukkan bahwa hanya 11 jam (dari 24 jam) yang menyumbang 70% dari total peminjaman. Batas 70% tercapai di jam 14.00, artinya setelah jam tersebut, kontribusi tambahan hanya 30% untuk 10 jam sisanya.

Perbedaan Pola Hari Kerja vs Akhir Pekan: Visualisasi perbandingan menunjukkan perbedaan yang sangat mencolok. Pada hari kerja, pola berbentuk 'M' dengan dua puncak di pagi dan sore. Pada akhir pekan, pola lebih datar dengan puncak di siang hari (jam 12.00-14.00), mencerminkan penggunaan rekreasi.

- Insight dari Visualisasi Pertanyaan 2 (Dampak Cuaca pada Akhir Pekan di Musim Gugur):

Penurunan Drastis akibat Cuaca Buruk: Bar chart menunjukkan bahwa pada akhir pekan di musim gugur, cuaca hujan ringan menyebabkan penurunan peminjaman sebesar 68.2% (dari 219 menjadi hanya 70 sepeda per jam). Ini adalah penurunan yang sangat signifikan dan perlu menjadi perhatian manajemen.

Kelembaban sebagai Indikator Kritis: Scatter plot menunjukkan hubungan negatif yang kuat antara kelembaban dan jumlah peminjaman. Ketika kelembaban melebihi 0.75 (garis ungu putus-putus), peminjaman cenderung turun drastis di bawah 100 sepeda per jam. Ini menjadikan kelembaban sebagai indikator yang baik untuk memprediksi penurunan permintaan.

Distribusi Data yang Berbeda per Kondisi Cuaca: Boxplot menunjukkan bahwa pada cuaca cerah, distribusi peminjaman cenderung tinggi dan menyebar (ada banyak variasi). Pada cuaca hujan, distribusi sangat rendah dan sempit (semua data rendah), mengindikasikan bahwa hujan benar-benar menghentikan aktivitas bersepeda.

## Analisis Lanjutan (Opsional)
"""

# ============================================
# 1 RFM ANALYSIS (UNTUK DATA HARIAN)
# ============================================

print("\n 1 RFM ANALYSIS (Recency, Frequency, Monetary)")
print("-"*50)

# Gunakan data harian (day.csv) untuk analisis RFM
df_day_clean = df_day_clean.copy()
df_day_clean['dteday'] = pd.to_datetime(df_day_clean['dteday'])

# Tentukan tanggal referensi (tanggal terakhir dalam dataset)
reference_date = df_day_clean['dteday'].max()

# Hitung Recency (hari sejak terakhir peminjaman)
rfm = df_day_clean.groupby('dteday').agg({
    'instant': 'count',  # Frequency
    'cnt': 'sum'         # Monetary
}).reset_index()
rfm.columns = ['dteday', 'frequency', 'monetary']

# Hitung recency (hari sejak tanggal referensi)
rfm['recency'] = (reference_date - rfm['dteday']).dt.days

# Buat score (1-4) untuk setiap metrik
rfm['R_score'] = pd.qcut(rfm['recency'], 4, labels=['4', '3', '2', '1']).astype(int)
rfm['F_score'] = pd.qcut(rfm['frequency'].rank(method='first'), 4, labels=['1', '2', '3', '4']).astype(int)
rfm['M_score'] = pd.qcut(rfm['monetary'], 4, labels=['1', '2', '3', '4']).astype(int)

# Hitung total RFM score
rfm['RFM_score'] = rfm['R_score'] + rfm['F_score'] + rfm['M_score']

# Segmentasi pelanggan
def rfm_segmentation(row):
    if row['R_score'] >= 3 and row['F_score'] >= 3 and row['M_score'] >= 3:
        return 'Champions (Paling Aktif)'
    elif row['R_score'] >= 3 and row['F_score'] >= 2:
        return 'Loyal (Setia)'
    elif row['R_score'] <= 2 and row['F_score'] >= 3 and row['M_score'] >= 3:
        return 'At Risk (Berisiko)'
    elif row['R_score'] <= 2 and row['F_score'] <= 2:
        return 'Lost (Hilang)'
    else:
        return 'Others'

rfm['segment'] = rfm.apply(rfm_segmentation, axis=1)

print("\n DISTRIBUSI SEGMEN PELANGGAN:")
segment_counts = rfm['segment'].value_counts()
for segment, count in segment_counts.items():
    pct = (count / len(rfm)) * 100
    print(f"   - {segment}: {count} hari ({pct:.1f}%)")

# Visualisasi RFM
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# R-Score Distribution
axes[0].hist(rfm['R_score'], bins=4, edgecolor='black', color='steelblue', alpha=0.7)
axes[0].set_title('Distribusi Recency Score', fontsize=12)
axes[0].set_xlabel('R-Score (1=terlama, 4=terbaru)')
axes[0].set_ylabel('Jumlah Hari')

# F-Score Distribution
axes[1].hist(rfm['F_score'], bins=4, edgecolor='black', color='coral', alpha=0.7)
axes[1].set_title('Distribusi Frequency Score', fontsize=12)
axes[1].set_xlabel('F-Score (1=terendah, 4=tertinggi)')
axes[1].set_ylabel('Jumlah Hari')

# M-Score Distribution
axes[2].hist(rfm['M_score'], bins=4, edgecolor='black', color='green', alpha=0.7)
axes[2].set_title('Distribusi Monetary Score', fontsize=12)
axes[2].set_xlabel('M-Score (1=terendah, 4=tertinggi)')
axes[2].set_ylabel('Jumlah Hari')

plt.tight_layout()
plt.show()

# ============================================
# 2 CLUSTERING BERDASARKAN JAM DAN CUACA
# ============================================

print("\n 2 CLUSTERING POLA PEMINJAMAN")
print("-"*50)

# Buat pivot table untuk melihat pola peminjaman per jam per kondisi cuaca
hour_weather_pivot = df.groupby(['hr', 'weather_label'])['cnt'].mean().reset_index()
hour_weather_pivot = hour_weather_pivot.pivot(index='hr', columns='weather_label', values='cnt').fillna(0)

print("\n RATA-RATA PEMINJAMAN PER JAM PER KONDISI CUACA:")
print("-"*70)
print(hour_weather_pivot.round(0))

# Identifikasi cluster jam berdasarkan pola peminjaman
def classify_hour(hour):
    if 6 <= hour <= 9:
        return 'Morning Peak (06:00-09:00)'
    elif 17 <= hour <= 19:
        return 'Evening Peak (17:00-19:00)'
    elif 10 <= hour <= 16:
        return 'Midday (10:00-16:00)'
    elif 20 <= hour <= 23:
        return 'Night (20:00-23:00)'
    else:
        return 'Early Morning/Late Night (00:00-05:00)'

df['hour_cluster'] = df['hr'].apply(classify_hour)

# Hitung rata-rata peminjaman per cluster
cluster_stats = df.groupby('hour_cluster').agg({
    'cnt': ['mean', 'std', 'count']
}).round(2)
cluster_stats.columns = ['mean_cnt', 'std_cnt', 'count']
cluster_stats = cluster_stats.reset_index()

print("\n STATISTIK PER CLUSTER JAM:")
print("-"*70)
for _, row in cluster_stats.iterrows():
    print(f"   {row['hour_cluster']}:")
    print(f"      - Rata-rata: {row['mean_cnt']:.0f} sepeda/jam")
    print(f"      - Std Dev: {row['std_cnt']:.0f}")
    print(f"      - Jumlah data: {row['count']:,} jam")

# Visualisasi clustering
fig, ax = plt.subplots(figsize=(12, 6))

cluster_colors = {
    'Morning Peak (06:00-09:00)': '#e74c3c',
    'Evening Peak (17:00-19:00)': '#e67e22',
    'Midday (10:00-16:00)': '#3498db',
    'Night (20:00-23:00)': '#2ecc71',
    'Early Morning/Late Night (00:00-05:00)': '#95a5a6'
}

hourly_mean = df.groupby('hr')['cnt'].mean().reset_index()
hourly_mean['cluster'] = hourly_mean['hr'].apply(classify_hour)

for cluster, color in cluster_colors.items():
    cluster_data = hourly_mean[hourly_mean['cluster'] == cluster]
    ax.scatter(cluster_data['hr'], cluster_data['cnt'],
               color=color, s=100, alpha=0.7, label=cluster, edgecolors='white', linewidth=1.5)

ax.plot(hourly_mean['hr'], hourly_mean['cnt'], color='black', alpha=0.3, linewidth=1)

ax.set_title('Pengelompokan Pola Peminjaman Berdasarkan Jam (Clustering)',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Jam', fontsize=12)
ax.set_ylabel('Rata-rata Jumlah Peminjaman', fontsize=12)
ax.set_xticks(range(0, 24))
ax.set_xticklabels([f'{i:02d}:00' for i in range(0, 24)], rotation=45)
ax.legend(loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

"""## Conclusion & Recommendation

- **Conclusion pertanyaan 1:** Peak Hour pada Hari Kerja
Berdasarkan analisis data peminjaman sepeda selama 2 tahun (2011-2012) pada hari kerja (workingday = 1), ditemukan bahwa:
1.   Terdapat 11 jam yang menyumbang 70.1% dari total peminjaman, yaitu jam 07.00 hingga jam 17.00. Peak hour utama terjadi pada dua periode:
Morning Peak (Pagi): Jam 07.00 - 09.00, dengan puncak tertinggi di jam 08.00 (total 189.921 peminjaman selama 2 tahun).
Evening Peak (Sore): Jam 17.00 - 19.00, dengan puncak tertinggi di jam 17.00 (total 170.302 peminjaman).

2.   Pola peminjaman antara hari kerja dan akhir pekan sangat berbeda:
Hari Kerja: Pola berbentuk 'M' dengan dua puncak di pagi dan sore hari, mencerminkan perilaku komuter (pergi dan pulang kerja/sekolah).
Akhir Pekan/Libur: Pola lebih datar dengan puncak di siang hari (jam 12.00-14.00), mencerminkan perilaku rekreasi.

3.   Jam dengan peminjaman terendah terjadi pada dini hari (jam 02.00-05.00), dengan rata-rata di bawah 20 sepeda per jam.

- **Conclusion pertanyaan 2:** Dampak Cuaca pada Akhir Pekan di Musim Gugur
Berdasarkan analisis data pada akhir pekan (workingday = 0) di musim gugur (season = 3), ditemukan bahwa:
1.   Kondisi cuaca memiliki dampak yang sangat signifikan terhadap jumlah peminjaman sepeda:
Cerah/Berawan: Rata-rata 219 sepeda per jam (baseline).
Berkabut: Rata-rata 147 sepeda per jam (penurunan 32.8%), dengan kelembaban rata-rata 0.73.
Hujan Ringan: Rata-rata 70 sepeda per jam (penurunan 68.2%), dengan kelembaban rata-rata 0.85.

2.   Faktor dominan penyebab penurunan >50% adalah kombinasi dari:
Kelembaban tinggi (>0.75)
Hujan atau salju ringan (weathersit = 3)
Suhu yang lebih rendah (rata-rata 0.45 vs 0.58 pada cuaca cerah)

3.   Korelasi antara kelembaban dan peminjaman bersifat negatif kuat: Scatter plot menunjukkan bahwa ketika kelembaban melebihi 0.75, peminjaman cenderung turun drastis di bawah 100 sepeda per jam.

**Rekomendasi Action Item:**
- 1. Optimalisasi Operasional (Rebalancing) untuk Segmen Komuter

Waktu dan	Aksi yang Direkomendasikan
- 06.00 - 07.00	Mulai rebalancing sepeda dari stasiun pusat kota ke stasiun pemukiman untuk mengantisipasi morning peak
- 07.00 - 09.00	Tambah staf operasional di stasiun tersibuk, pastikan semua sepeda berfungsi baik
- 15.00 - 16.00	Mulai rebalancing sepeda dari stasiun pemukiman kembali ke pusat kota untuk mengantisipasi evening peak
- 17.00 - 19.00	Tambah staf, pastikan stasiun pusat kota memiliki ketersediaan sepeda yang cukup
- 20.00 - 05.00	Lakukan maintenance dan pengisian ulang sepeda di seluruh stasiun

- 2. Strategi Mitigasi Dampak Cuaca dengan Promosi Dinamis

Kondisi Cuaca dan	Action Item
- Cerah	Fokus pada promosi "Day Pass" dan rute wisata untuk segmen rekreasi di akhir pekan
- Berkabut	Kirim notifikasi "Foggy Ride - Double Points!" dengan diskon 10% untuk perjalanan pertama
- Hujan Ringan	Kirim promo "Rainy Day Special" diskon 20% + gratis jas hujan di stasiun utama (gunaannya jastip)
- Hujan Lebat	Alihkan promosi ke layanan ride-hailing partner (strategi partnership) + tawarkan credit untuk hari berikutnya
"""