# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_1vu2BxmAd-pnEOfuQwqG1bRad-P6L4
"""

# ============================================
# DASHBOARD ANALISIS BIKE SHARING
# ============================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# ============================================
# KONFIGURASI HALAMAN
# ============================================
st.set_page_config(
    page_title="Bike Sharing Dashboard",
    page_icon="🚲",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================
# LOAD DATA (CACHED)
# ============================================
@st.cache_data
def load_hourly_data():
    df = pd.read_csv('data_1.csv', parse_dates=['dteday'])
    
    # Tambahkan kolom yang diperlukan jika belum ada
    if 'year' not in df.columns:
        df['year'] = df['dteday'].dt.year
    
    if 'month_name' not in df.columns:
        df['month_name'] = df['dteday'].dt.month_name()
    
    # Mapping untuk label
    season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
    weather_map = {1: 'Clear', 2: 'Mist', 3: 'Light Rain/Snow', 4: 'Heavy Rain/Snow'}
    day_type_map = {1: 'Working Day', 0: 'Weekend/Holiday'}
    
    df['season_label'] = df['season'].map(season_map)
    df['weather_label'] = df['weathersit'].map(weather_map)
    df['day_type'] = df['workingday'].map(day_type_map)
    
    return df

@st.cache_data
def load_daily_data():
    df = pd.read_csv('data_1.csv', parse_dates=['dteday'])
    df['year'] = df['dteday'].dt.year
    
    # Mapping untuk label
    season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
    weather_map = {1: 'Clear', 2: 'Mist', 3: 'Light Rain/Snow', 4: 'Heavy Rain/Snow'}
    day_type_map = {1: 'Working Day', 0: 'Weekend/Holiday'}
    
    df['season_label'] = df['season'].map(season_map)
    df['weather_label'] = df['weathersit'].map(weather_map)
    df['day_type'] = df['workingday'].map(day_type_map)
    
    return df

# Load data
hourly_df = load_hourly_data()
daily_df = load_daily_data()

# ============================================
# SIDEBAR FILTER
# ============================================
st.sidebar.title("🚲 Bike Sharing Dashboard")
st.sidebar.markdown("---")
st.sidebar.markdown("### Filter Data")

# Filter Tahun
years = sorted(hourly_df['year'].unique())
selected_year = st.sidebar.multiselect(
    "📅 Tahun",
    options=years,
    default=years,
    format_func=lambda x: f"{x}"
)

# Filter Musim
seasons = sorted(hourly_df['season_label'].dropna().unique())
selected_season = st.sidebar.multiselect(
    "🍂 Musim",
    options=seasons,
    default=seasons
)

# Filter Kondisi Cuaca
weathers = sorted(hourly_df['weather_label'].dropna().unique())
selected_weather = st.sidebar.multiselect(
    "🌤️ Kondisi Cuaca",
    options=weathers,
    default=weathers
)

# Filter Tipe Hari
day_types = sorted(hourly_df['day_type'].dropna().unique())
selected_day_type = st.sidebar.multiselect(
    "📆 Tipe Hari",
    options=day_types,
    default=day_types
)

# Apply Filters
filtered_df = hourly_df[
    (hourly_df['year'].isin(selected_year)) &
    (hourly_df['season_label'].isin(selected_season)) &
    (hourly_df['weather_label'].isin(selected_weather)) &
    (hourly_df['day_type'].isin(selected_day_type))
]

filtered_daily = daily_df[
    (daily_df['year'].isin(selected_year)) &
    (daily_df['season_label'].isin(selected_season)) &
    (daily_df['weather_label'].isin(selected_weather)) &
    (daily_df['day_type'].isin(selected_day_type))
]

# ============================================
# METRIK UTAMA
# ============================================
st.title("🚲 Bike Sharing Dashboard")
st.markdown("Analisis Peminjaman Sepeda Capital Bikeshare Washington D.C. (2011-2012)")
st.markdown("---")

# Hitung metrik
total_rentals = filtered_df['cnt'].sum()
avg_rentals = filtered_df['cnt'].mean()
max_rentals = filtered_df['cnt'].max()
total_days = filtered_daily['dteday'].nunique()

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("📊 Total Peminjaman", f"{total_rentals:,.0f}")
with col2:
    st.metric("⏱️ Rata-rata per Jam", f"{avg_rentals:.0f}")
with col3:
    st.metric("🔥 Peminjaman Tertinggi", f"{max_rentals:,.0f}")
with col4:
    st.metric("📅 Hari Aktif", f"{total_days}")

st.markdown("---")
st.success("✅ Dashboard berhasil dimuat! Silakan gunakan filter di sidebar untuk eksplorasi data.")
