# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_1vu2BxmAd-pnEOfuQwqG1bRad-P6L4
"""

import pandas as pd
import numpy as np
from datetime import datetime

# Load data yang sudah dibersihkan (pastikan df_hour_clean sudah ada)
# Jika belum, load dari file CSV
try:
    df_hourly = pd.read_csv('/content/data_1.csv')
    print("✅ Data berhasil dimuat dari file")
except:
    print("⚠️ Gunakan df_hour_clean yang sudah ada dari proses sebelumnya")
    df_hourly = df_hour_clean.copy()

# Konversi tipe data
df_hourly['dteday'] = pd.to_datetime(df_hourly['dteday'])
df_hourly['year'] = df_hourly['dteday'].dt.year
df_hourly['month'] = df_hourly['dteday'].dt.month
df_hourly['month_name'] = df_hourly['dteday'].dt.month_name()
df_hourly['day'] = df_hourly['dteday'].dt.day
df_hourly['day_name'] = df_hourly['dteday'].dt.day_name()

# Mapping untuk label
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
weather_map = {1: 'Clear', 2: 'Mist', 3: 'Light Rain/Snow', 4: 'Heavy Rain/Snow'}
day_type_map = {1: 'Working Day', 0: 'Weekend/Holiday'}

df_hourly['season_label'] = df_hourly['season'].map(season_map)
df_hourly['weather_label'] = df_hourly['weathersit'].map(weather_map)
df_hourly['day_type'] = df_hourly['workingday'].map(day_type_map)

# Buat data agregat harian
df_daily = df_hourly.groupby('dteday').agg({
    'cnt': 'sum',
    'casual': 'sum',
    'registered': 'sum',
    'temp': 'mean',
    'hum': 'mean',
    'windspeed': 'mean',
    'season': 'first',
    'season_label': 'first',
    'yr': 'first',
    'workingday': 'first',
    'weathersit': 'first',
    'weather_label': 'first',
    'day_type': 'first'
}).reset_index()

df_daily['year'] = df_daily['dteday'].dt.year

# Simpan ke file CSV untuk dashboard
df_hourly.to_csv('/content/hourly_data.csv', index=False)
df_daily.to_csv('/content/daily_data.csv', index=False)

print("\n✅ Data berhasil disiapkan untuk dashboard!")
print(f"   - hourly_data.csv: {len(df_hourly):,} baris")
print(f"   - daily_data.csv: {len(df_daily)} baris")
print("\n📁 Folder 'dashboard' telah dibuat dengan file data CSV")

# ============================================
# DASHBOARD ANALISIS BIKE SHARING
# ============================================
# Nama File: dashboard.py
# Cara menjalankan: streamlit run dashboard.py
# ============================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# ============================================
# KONFIGURASI HALAMAN
# ============================================
st.set_page_config(
    page_title="Bike Sharing Dashboard",
    page_icon="🚲",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================
# LOAD DATA (CACHED)
# ============================================
@st.cache_data
def load_hourly_data():
    df = pd.read_csv('/content/hourly_data.csv', parse_dates=['dteday'])
    return df

@st.cache_data
def load_daily_data():
    df = pd.read_csv('/content/daily_data.csv', parse_dates=['dteday'])
    return df

hourly_df = load_hourly_data()
daily_df = load_daily_data()

# ============================================
# SIDEBAR FILTER
# ============================================
st.sidebar.title("🚲 Bike Sharing Dashboard")
st.sidebar.markdown("---")
st.sidebar.markdown("### Filter Data")

# Filter Tahun
years = sorted(hourly_df['year'].unique())
selected_year = st.sidebar.multiselect(
    "📅 Tahun",
    options=years,
    default=years,
    format_func=lambda x: f"{x}"
)

# Filter Musim
seasons = sorted(hourly_df['season_label'].unique())
selected_season = st.sidebar.multiselect(
    "🍂 Musim",
    options=seasons,
    default=seasons
)

# Filter Kondisi Cuaca
weathers = sorted(hourly_df['weather_label'].unique())
selected_weather = st.sidebar.multiselect(
    "🌤️ Kondisi Cuaca",
    options=weathers,
    default=weathers
)

# Filter Tipe Hari
day_types = sorted(hourly_df['day_type'].unique())
selected_day_type = st.sidebar.multiselect(
    "📆 Tipe Hari",
    options=day_types,
    default=day_types
)

# Apply Filters
filtered_df = hourly_df[
    (hourly_df['year'].isin(selected_year)) &
    (hourly_df['season_label'].isin(selected_season)) &
    (hourly_df['weather_label'].isin(selected_weather)) &
    (hourly_df['day_type'].isin(selected_day_type))
]

filtered_daily = daily_df[
    (daily_df['year'].isin(selected_year)) &
    (daily_df['season_label'].isin(selected_season)) &
    (daily_df['weather_label'].isin(selected_weather)) &
    (daily_df['day_type'].isin(selected_day_type))
]

# ============================================
# METRIK UTAMA
# ============================================
st.title("🚲 Bike Sharing Dashboard")
st.markdown("Analisis Peminjaman Sepeda Capital Bikeshare Washington D.C. (2011-2012)")
st.markdown("---")

# Hitung metrik
total_rentals = filtered_df['cnt'].sum()
avg_rentals = filtered_df['cnt'].mean()
max_rentals = filtered_df['cnt'].max()
total_days = filtered_daily['dteday'].nunique()

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("📊 Total Peminjaman", f"{total_rentals:,.0f}")
with col2:
    st.metric("⏱️ Rata-rata per Jam", f"{avg_rentals:.0f}")
with col3:
    st.metric("🔥 Peminjaman Tertinggi", f"{max_rentals:,.0f}")
with col4:
    st.metric("📅 Hari Aktif", f"{total_days}")

st.markdown("---")

# ============================================
# VISUALISASI 1: PEAK HOUR ANALYSIS
# ============================================
st.header("⏰ Analisis Peak Hour pada Hari Kerja")
st.markdown("Visualisasi ini menjawab pertanyaan: *Jam berapa peak hour yang menyumbang 70% peminjaman?*")

# Filter untuk hari kerja
workingday_df = filtered_df[filtered_df['day_type'] == 'Working Day']

if len(workingday_df) > 0:
    # Hitung total per jam
    hourly_total = workingday_df.groupby('hr')['cnt'].sum().reset_index()
    hourly_total.columns = ['hour', 'total_cnt']
    hourly_total['percentage'] = (hourly_total['total_cnt'] / hourly_total['total_cnt'].sum()) * 100
    hourly_total['cumulative_pct'] = hourly_total['percentage'].cumsum()
    hourly_total['is_peak'] = hourly_total['cumulative_pct'] <= 70

    peak_hours = hourly_total[hourly_total['is_peak']]['hour'].tolist()
    peak_contribution = hourly_total[hourly_total['is_peak']]['percentage'].sum()

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Jumlah Peak Hours", f"{len(peak_hours)} jam",
                  help=f"Jam: {', '.join([f'{h:02d}:00' for h in peak_hours])}")
    with col2:
        st.metric("Kontribusi Peak Hours", f"{peak_contribution:.1f}%")

    # Bar Chart Peak Hour (Plotly)
    colors = ['coral' if is_peak else 'steelblue' for is_peak in hourly_total['is_peak']]
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=hourly_total['hour'],
        y=hourly_total['total_cnt'],
        marker_color=colors,
        text=hourly_total['total_cnt'],
        textposition='outside',
        name='Total Peminjaman'
    ))
    fig.add_hline(y=hourly_total['total_cnt'].mean(), line_dash="dash", line_color="green",
                  annotation_text=f"Rata-rata: {hourly_total['total_cnt'].mean():.0f}")
    fig.update_layout(
        title='Total Peminjaman per Jam pada Hari Kerja',
        xaxis_title='Jam',
        yaxis_title='Total Peminjaman',
        xaxis=dict(tickmode='linear', tick0=0, dtick=2),
        height=450
    )
    st.plotly_chart(fig, use_container_width=True)

    # Cumulative Chart
    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(
        x=hourly_total['hour'],
        y=hourly_total['cumulative_pct'],
        mode='lines+markers',
        name='Kumulatif',
        line=dict(color='steelblue', width=2),
        marker=dict(size=6, color='steelblue')
    ))
    fig2.add_hline(y=70, line_dash="dash", line_color="red", annotation_text="Batas 70%")
    fig2.add_hrect(y0=0, y1=70, line_width=0, fillcolor="coral", opacity=0.2)
    fig2.update_layout(
        title='Kontribusi Kumulatif Peminjaman per Jam',
        xaxis_title='Jam',
        yaxis_title='Persentase Kumulatif (%)',
        xaxis=dict(tickmode='linear', tick0=0, dtick=2),
        height=450
    )
    st.plotly_chart(fig2, use_container_width=True)

    # Insight
    st.info(f"💡 **Insight**: {len(peak_hours)} jam pertama (jam {peak_hours[0]:02d}:00 - {peak_hours[-1]:02d}:00) "
            f"menyumbang {peak_contribution:.1f}% dari total peminjaman pada hari kerja. "
            f"Puncak tertinggi terjadi pada jam 08:00 pagi dan jam 17:00-18:00 sore.")
else:
    st.warning("Tidak ada data untuk hari kerja dengan filter yang dipilih.")

st.markdown("---")

# ============================================
# VISUALISASI 2: DAMPAK CUACA
# ============================================
st.header("🌤️ Dampak Cuaca pada Akhir Pekan di Musim Gugur")
st.markdown("Visualisasi ini menjawab pertanyaan: *Faktor cuaca apa yang menyebabkan penurunan >50%?*")

# Filter untuk akhir pekan di musim gugur
weekend_fall = filtered_df[(filtered_df['day_type'] == 'Weekend/Holiday') &
                           (filtered_df['season_label'] == 'Fall')]

if len(weekend_fall) > 0:
    # Analisis per kondisi cuaca
    weather_impact = weekend_fall.groupby('weather_label')['cnt'].agg(['mean', 'count']).reset_index()
    weather_impact.columns = ['weather_label', 'mean_cnt', 'count']

    # Hitung baseline dan penurunan
    baseline = weather_impact[weather_impact['weather_label'] == 'Clear']['mean_cnt'].values[0]
    weather_impact['decline_pct'] = ((baseline - weather_impact['mean_cnt']) / baseline) * 100
    weather_impact['decline_pct'] = weather_impact['decline_pct'].clip(lower=0)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("☀️ Cuaca Cerah", f"{baseline:.0f} sepeda/jam")
    with col2:
        mist_data = weather_impact[weather_impact['weather_label'] == 'Mist']
        if len(mist_data) > 0:
            st.metric("🌫️ Cuaca Berkabut", f"{mist_data['mean_cnt'].values[0]:.0f} sepeda/jam",
                      delta=f"-{mist_data['decline_pct'].values[0]:.1f}%", delta_color="inverse")
    with col3:
        rain_data = weather_impact[weather_impact['weather_label'] == 'Light Rain/Snow']
        if len(rain_data) > 0:
            st.metric("🌧️ Hujan Ringan", f"{rain_data['mean_cnt'].values[0]:.0f} sepeda/jam",
                      delta=f"-{rain_data['decline_pct'].values[0]:.1f}%", delta_color="inverse")

    # Bar Chart
    fig3 = px.bar(
        weather_impact,
        x='weather_label',
        y='mean_cnt',
        color='mean_cnt',
        color_continuous_scale='RdYlGn_r',
        title='Rata-rata Peminjaman per Kondisi Cuaca',
        labels={'weather_label': 'Kondisi Cuaca', 'mean_cnt': 'Rata-rata Peminjaman'}
    )
    fig3.update_layout(height=450)
    st.plotly_chart(fig3, use_container_width=True)

    # Scatter plot humidity vs count
    fig4 = px.scatter(
        weekend_fall,
        x='hum',
        y='cnt',
        color='weather_label',
        title='Hubungan Kelembaban vs Jumlah Peminjaman',
        labels={'hum': 'Kelembaban', 'cnt': 'Jumlah Peminjaman'},
        color_discrete_map={'Clear': '#2ecc71', 'Mist': '#f39c12', 'Light Rain/Snow': '#e74c3c'}
    )
    fig4.add_hline(y=100, line_dash="dash", line_color="red", annotation_text="Batas Kritis 100")
    fig4.add_vline(x=0.75, line_dash="dash", line_color="purple", annotation_text="Kelembaban Kritis 0.75")
    fig4.update_layout(height=450)
    st.plotly_chart(fig4, use_container_width=True)

    # Insight
    rain_decline = weather_impact[weather_impact['weather_label'] == 'Light Rain/Snow']['decline_pct'].values[0] if len(weather_impact[weather_impact['weather_label'] == 'Light Rain/Snow']) > 0 else 0
    st.info(f"💡 **Insight**: Pada akhir pekan di musim gugur, cuaca hujan ringan menurunkan peminjaman "
            f"hingga {rain_decline:.1f}% dibandingkan cuaca cerah. "
            f"Kelembaban tinggi (>0.75) menjadi indikator kritis penurunan permintaan.")
else:
    st.warning("Tidak ada data untuk akhir pekan di musim gugur dengan filter yang dipilih.")

st.markdown("---")

# ============================================
# VISUALISASI 3: PERBANDINGAN HARI KERJA VS AKHIR PEKAN
# ============================================
st.header("📆 Perbandingan Pola: Hari Kerja vs Akhir Pekan")

# Prepare data
hourly_pattern = filtered_df.groupby(['hr', 'day_type'])['cnt'].mean().reset_index()

fig5 = px.line(
    hourly_pattern,
    x='hr',
    y='cnt',
    color='day_type',
    title='Perbandingan Pola Peminjaman: Hari Kerja vs Akhir Pekan/Libur',
    labels={'hr': 'Jam', 'cnt': 'Rata-rata Jumlah Peminjaman'},
    markers=True
)
fig5.add_vrect(x0=7, x1=9, line_width=0, fillcolor="blue", opacity=0.1, annotation_text="Morning Peak")
fig5.add_vrect(x0=17, x1=19, line_width=0, fillcolor="orange", opacity=0.1, annotation_text="Evening Peak")
fig5.add_vrect(x0=12, x1=14, line_width=0, fillcolor="green", opacity=0.1, annotation_text="Afternoon Peak")
fig5.update_layout(height=500, xaxis=dict(tickmode='linear', tick0=0, dtick=2))
st.plotly_chart(fig5, use_container_width=True)

st.info("💡 **Insight**: Hari kerja memiliki dua puncak (pagi dan sore) mencerminkan perilaku komuter, "
        "sedangkan akhir pekan memiliki puncak di siang hari mencerminkan penggunaan rekreasi.")

st.markdown("---")

# ============================================
# VISUALISASI 4: TREN MUSIMAN DAN TAHUNAN
# ============================================
st.header("🍂 Analisis Tren Musiman dan Tahunan")

col1, col2 = st.columns(2)

with col1:
    # Tren per musim
    seasonal_stats = filtered_df.groupby('season_label')['cnt'].mean().reset_index()
    seasonal_stats = seasonal_stats.sort_values('cnt', ascending=False)

    fig6 = px.bar(
        seasonal_stats,
        x='season_label',
        y='cnt',
        color='cnt',
        color_continuous_scale='Viridis',
        title='Rata-rata Peminjaman per Musim',
        labels={'season_label': 'Musim', 'cnt': 'Rata-rata Peminjaman'}
    )
    fig6.update_layout(height=400)
    st.plotly_chart(fig6, use_container_width=True)

with col2:
    # Tren per tahun
    yearly_stats = filtered_df.groupby('year')['cnt'].mean().reset_index()

    fig7 = px.bar(
        yearly_stats,
        x='year',
        y='cnt',
        color='cnt',
        color_continuous_scale='Blues',
        title='Rata-rata Peminjaman per Tahun',
        labels={'year': 'Tahun', 'cnt': 'Rata-rata Peminjaman'}
    )
    fig7.update_layout(height=400)
    st.plotly_chart(fig7, use_container_width=True)

# Tren bulanan
monthly_stats = filtered_df.groupby('month_name')['cnt'].mean().reset_index()
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']
monthly_stats['month_name'] = pd.Categorical(monthly_stats['month_name'], categories=month_order, ordered=True)
monthly_stats = monthly_stats.sort_values('month_name')

fig8 = px.line(
    monthly_stats,
    x='month_name',
    y='cnt',
    title='Rata-rata Peminjaman per Bulan',
    labels={'month_name': 'Bulan', 'cnt': 'Rata-rata Peminjaman'},
    markers=True
)
fig8.update_layout(height=450)
st.plotly_chart(fig8, use_container_width=True)

st.info("💡 **Insight**: Musim Gugur (Fall) memiliki rata-rata peminjaman tertinggi, "
        "terjadi peningkatan signifikan dari tahun 2011 ke 2012, "
        "dan puncak peminjaman bulanan terjadi di bulan September.")

st.markdown("---")

# ============================================
# REKOMENDASI
# ============================================
st.header("💡 Rekomendasi Strategis")

tab1, tab2, tab3 = st.tabs(["📌 Operasional Rebalancing", "📌 Mitigasi Cuaca", "📌 Program Loyalitas"])

with tab1:
    st.markdown("""
    ### Optimalisasi Operasional Berdasarkan Peak Hour

    | Jam | Aksi yang Direkomendasikan |
    |-----|---------------------------|
    | **06.00 - 07.00** | Mulai rebalancing sepeda dari pusat kota ke pemukiman |
    | **07.00 - 09.00** | Tambah staf di stasiun tersibuk, pastikan ketersediaan sepeda |
    | **15.00 - 16.00** | Mulai rebalancing sepeda dari pemukiman ke pusat kota |
    | **17.00 - 19.00** | Tambah staf, pastikan stasiun pusat kota memiliki cukup sepeda |

    **Target**: Mengurangi keluhan "sepeda habis" di jam sibuk hingga 50%
    """)

with tab2:
    st.markdown("""
    ### Strategi Mitigasi Dampak Cuaca

    | Kondisi Cuaca | Action Item |
    |---------------|-------------|
    | **☀️ Cerah** | Fokus pada promosi "Day Pass" dan rute wisata |
    | **🌫️ Berkabut** | Kirim notifikasi "Foggy Ride - Double Points!" diskon 10% |
    | **🌧️ Hujan Ringan** | Promo "Rainy Day Special" diskon 20% + jas hujan gratis |
    | **⛈️ Hujan Lebat** | Alihkan promosi ke layanan ride-hailing partner |

    **Target**: Meningkatkan peminjaman pada cuaca buruk hingga 30%
    """)

with tab3:
    st.markdown("""
    ### Program Loyalitas Pengguna

    1. **Weather Guarantee Program**
       - Refund 100% jika hujan dalam 30 menit setelah peminjaman
       - Membangun kepercayaan pengguna

    2. **Peak Hour Member Discount**
       - Diskon khusus untuk peminjaman di jam non-peak (10:00-16:00)
       - Mendistribusikan beban operasional

    3. **Seasonal Pass**
       - Paket berlangganan musiman dengan harga lebih murah
       - Khusus untuk musim gugur (peminjaman tertinggi)

    **Target**: Meningkatkan retensi pelanggan hingga 40%
    """)

st.markdown("---")
st.caption("Dashboard ini dibuat untuk proyek akhir analisis data | Dataset: Capital Bikeshare (2011-2012)")
